version: '3'
services:
    db:
        image: "postgres"
        container_name: db
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=askai

    app:
        build: .
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db/askai
            - OPENAI_API_KEY=your-openai-api-key-here # <-- User should replace this value
        ports:
            - 5000:5000